### PR TITLE
Add /facepalm and /laugh

### PR DESCRIPTION
**Pull request by t3rav0lt**
Feel free to correct syntax in the command code if I got some stuff wrong.

### CODE REVIEW

**Comment by t3rav0lt** [comment]
I have **_NO IDEA_** why the pull request decided to drag 7 other commits into my two file suggestions but oh well.

**Comment by ajaxvp** [comment]
i might need to change a few things, i'll merge it soon.

**Review by t3rav0lt — COMMENTED** [review]
Yep.

**Comment by ajaxvp** [comment]
you did your pr on the wrong branch. we're currently on the 1.14 branch. i committed all your changes to the 1.14 branch.

**Pull request closed without merging**
