### PR TITLE
Re-add TFM FrontDoor

### PR DESCRIPTION
**Pull request by Paldiu**
Updated case 8 to work regardless of worldguard presence in absence of the PROTECTED_AREAS flag in the config.yml

### CODE REVIEW

**Comment by ncurran02** [comment]
There is a lot of conflicts that need to be resolved.

**Comment by Paldiu** [comment]
> There is a lot of conflicts that need to be resolved.

Are you even a member of this project?

**Comment by ncurran02** [comment]
> > There is a lot of conflicts that need to be resolved.
> 
> Are you even a member of this project?

No but I don’t see why I’m not allowed to give my input...

**Comment by ncurran02** [comment]
And also (not sure if it’s intentional) you have proposed the PR on the wrong repo.

**Comment by Paldiu** [comment]
> And also (not sure if it’s intentional) you have proposed the PR on the wrong repo. 

This is the correct repo. The main TFM repo is not the repo we are currently working on, this repo is the freshest up to date model, and if you notice this is like 400 commits ahead of the main TFM repo.

**Comment by Paldiu** [comment]
This pull request is scheduled for deletion due to commit flooding. The FrontDoor class will be lifted out of this commit and transplanted into the development repo.

**Pull request closed without merging**
