### PR TITLE
Add Clan

### PR DESCRIPTION
**Pull request by ghost**
#32

### CODE REVIEW

**Comment by ncurran02** [comment]
Telnet Clan is a title extended from Telnet Admin giving them few more permissions. I don’t think we will need to make it a rank.

**Comment by ghost** [comment]
It was added as a rank @Focusvity because titles cannot be added [or taken away] by means of `/saconfig`, the configuration file has to be edited. The rank can be set without the need for them to be added in the configuration.

**Comment by ncurran02** [comment]
The way we have is just fine. If you want to have the title of `Telnet Clan.`, then set your login message and tag (`/myadmin settag` coming soon)

**Comment by lemonsked** [comment]
Needs owner/exec approval.

**Comment by untuned** [comment]
It shouldn't be needed now that /myadmin settag is done, but that's just me.

**Comment by robingall2910** [comment]
@untuned it shouldn't, refer to #32 again for my comment

**Comment by lemonsked** [comment]
See issue for why we don’t need this, but if admins want clan as a rank, this decision can be rethought once suggestion is approved

**Pull request closed without merging**
