### PR TITLE
Resolves #62

### LINKED ISSUE #62: Console can use adminworld
In telnet I can type /adminworld or /mbworld. It should be changed so this does not happen. You can change the SOURCETYPE to player so console can't execute it

### PR DESCRIPTION
**Pull request by Telesphoreo**

### CODE REVIEW

**Comment by ncurran02** [comment]
AdminWorld command can be used on console to execute /adminworld purge

**Comment by Telesphoreo** [comment]
oh yeah
then it should be changed so they can't tp then

**Comment by ncurran02** [comment]
It’s already added...

**Comment by Telesphoreo** [comment]
haha i'm tired

**Pull request closed without merging**
