### PR TITLE
add useful stuff to lockup

### PR DESCRIPTION
**Pull request by Deauthorized**
what this pr adds

- /lockup noob (needed if you need to lock up everyone except the admins)

- almost unbypassable (will freeze you so it's impossible to do anything else than just wait or disconnect)

- yet again fancy lockup gui

### CODE REVIEW

**Comment by Deauthorized** [comment]
it compiles completely fine ignore seths gay pom.xml

**Comment by ncurran02** [comment]
Again, do we really need this?

**Comment by Deauthorized** [comment]
> Again, do we really need this?

i mean there may be a situation where you have to lockup everyone except the admins

also i noticed you can still move while in lockup by spamming "esc"

**Comment by robingall2910** [comment]
we're not even supposed to use lockup unless it's really needed plus, no we don't need to lock up everyone, like ever, and yes we're aware, so what? you're gonna have to give up anyway, can't press escape forever so

ass

**Pull request closed without merging**
