### PR TITLE
Improve forbidden tags

### PR DESCRIPTION
**Pull request by ghost**
Adds forbidden tags that are otherwise not permitted.

### CODE REVIEW

**Comment by robingall2910** [comment]
exec/executive isn't a tag

**Comment by ghost** [comment]
@robingall2910 You still aren't allowed to have a title that implies a rank on TotalFreedom. We don't have "Moderator", either but it's still forbidden.

**Comment by untuned** [comment]
@pramire the tags aren't case sensitive, as when checking it lowercases the string to see if it matches any of the forbidden words.

**Comment by ghost** [comment]
Naturally @untuned

**Comment by ncurran02** [comment]
`"super_admin", "telnet_admin", "senior_admin"` can be removed. The method being used here is `contains`, so it will check if it contains that word, it will prevent it from setting.

**Comment by script-head** [comment]
SA, STA, TCA, and SrA are still uppercase.

**Pull request closed without merging**
