### PR TITLE
Bug fixes and improvements

### PR DESCRIPTION
**Pull request by script-head**

### CODE REVIEW

**Comment by ghost** [comment]
@ZeroEpoch1969 , LogFile module still is not added.

**Comment by ghost** [comment]
Plus my name?

**Comment by ghost** [comment]
@ZeroEpoch1969 , mind copying Lemon Module to let admins download the server Logfiles?

https://github.com/TotalFreedom/TotalFreedomMod/pull/1969

**Comment by script-head** [comment]
@marcocorriero Done

**Comment by ghost** [comment]
@ZeroEpoch1969 , perfect, this TFM can be sent to windows.

**Pull request merged**
