### PR TITLE
add extra stuff to doom

### PR DESCRIPTION
**Pull request by Deauthorized**
probably wont work as this is the first time i've touched a plugin, if it does thats cool

### CODE REVIEW

**Comment by robingall2910** [comment]
your build failed, you're missing a semicolon according to travis-ci

**Comment by Deauthorized** [comment]
> your build failed, you're missing a semicolon according to travis-ci

fuck ill go fix it lol

**Comment by lemonsked** [comment]
honestly I like it the way it currently is

**Comment by Deauthorized** [comment]
literally everything about this i somehow broke so i'm gonna go ahead and

**Pull request closed without merging**
