### PR TITLE
add command which lets super admins change the entity cap

### PR DESCRIPTION
**Pull request by Deauthorized**
this does 2 things

create a command (/entitycap)

- typing /entitycap will reset the entity cap back to 400

- typing /entitycap 200 will set the entity cap to 200

revert entitywiper back to supers version

-  seths version of entitywiper is kinda bad because it allows for the creation of massive amounts of entities crashing out the server before the server has a chance to clear them

and yes this actually does have a use this time, it allows for admins to dynamically control the entity wiper cap so it can be adjusted as needed

### CODE REVIEW

**Comment by ncurran02** [comment]
Why are you using ArrayList?

**Comment by Deauthorized** [comment]
> Why are you using ArrayList?

i have no idea tbh, integers are local to a method and mutable variables are "weird" according to people so i kinda had to use an array

is there anything else i could use which would work the same, im open to suggestions

**Comment by ncurran02** [comment]
> > Why are you using ArrayList?
> 
> i have no idea tbh, integers are local to a method and mutable variables are "weird" according to people so i kinda had to use an array
> 
> is there anything else i could use which would work the same, im open to suggestions

You can always store it in the config file.

**Comment by Deauthorized** [comment]
> > > Why are you using ArrayList?
> > 
> > 
> > i have no idea tbh, integers are local to a method and mutable variables are "weird" according to people so i kinda had to use an array
> > is there anything else i could use which would work the same, im open to suggestions
> 
> You can always store it in the config file.

i'll look into that, thanks

**Comment by Deauthorized** [comment]
ok now its less gay

**Comment by Deauthorized** [comment]
any suggestions? i personally think this is good enough

**Comment by Deauthorized** [comment]
i have another pr i'm going to submit soon after this one is merged, cant do it now because conflict issues would happen

**Comment by Ivanomoly** [comment]
no.

**Comment by Deauthorized** [comment]
y, dont see anything wrong with the code or pr

**Comment by Ivanomoly** [comment]
it's simply useless

**Comment by Deauthorized** [comment]
not sure how, the entity wiper i see running rn only runs on like 5 minute intervals, you can create pretty much as many entities as you want between those 5 minutes

**Comment by Deauthorized** [comment]
i am honestly confused

**Comment by ncurran02** [comment]
It’s quite useful but ok.

**Pull request closed without merging**
