### PR TITLE
Update /tban

### PR DESCRIPTION
**Pull request by ghost**
#28

### CODE REVIEW

**Comment by script-head** [comment]
This requires a forum vote before being merged.

**Comment by ghost** [comment]
Vote is open, http://totalfreedom.boards.net/thread/58383/improve-tempban

**Comment by script-head** [comment]
Once more votes are made on it I'll add up the votes and merge if it is accepted.

**Comment by ncurran02** [comment]
There's a conflict between the branch and his PR. This issue must be solved before it can be merged by a developer.

**Pull request closed without merging**
