### PR TITLE
At least test it

### PR DESCRIPTION
**Pull request by Telesphoreo**
It will still throw a NPE whenever the social links is like this
social_links: []
The way that it is written makes it so that it doesn't throw the NPE when the social links looks like this:
social_links: []

I fixed that bug and also another bug. You should use sender.sendMessage (or msg, or however TFM does it???) instead of lines.add, and fixed the wording of the message a little

### CODE REVIEW

**Comment by ncurran02** [comment]
Maybe fix the formatting?

**Comment by Telesphoreo** [comment]
@Focusvity I tried. It's pretty confusing with IntellIJ, but I'll have another look EDIT: fixed the else formatting, thats all that I could find

**Comment by ncurran02** [comment]
@Telesphoreo, what OS are you using?

**Comment by Telesphoreo** [comment]
@Focusvity Windows 10

**Comment by ncurran02** [comment]
@Telesphoreo Do `Ctrl` + `Alt` + `L` to format the file you are on.

**Comment by lemonsked** [comment]
put this in .idea\codeStyles\Project.xml and make sure its selected 
`<component name="ProjectCodeStyleConfiguration">
  <code_scheme name="Project" version="173">
    <codeStyleSettings language="JAVA">
      <option name="BRACE_STYLE" value="2" />
      <option name="CLASS_BRACE_STYLE" value="2" />
      <option name="METHOD_BRACE_STYLE" value="2" />
      <option name="LAMBDA_BRACE_STYLE" value="2" />
      <option name="ELSE_ON_NEW_LINE" value="true" />
      <option name="WHILE_ON_NEW_LINE" value="true" />
      <option name="CATCH_ON_NEW_LINE" value="true" />
      <option name="FINALLY_ON_NEW_LINE" value="true" />
      <option name="IF_BRACE_FORCE" value="3" />
      <option name="DOWHILE_BRACE_FORCE" value="3" />
      <option name="WHILE_BRACE_FORCE" value="3" />
      <option name="FOR_BRACE_FORCE" value="3" />
    </codeStyleSettings>
  </code_scheme>
</component>`

**Comment by Telesphoreo** [comment]
Tried Focusvity's idea. I don't have a codeStyles folder

**Comment by lemonsked** [comment]
you have to make the folder yourself

**Comment by Telesphoreo** [comment]
@OxLemonxO yes i realized that and i did that and i formatted it

**Pull request merged**
