### PR TITLE
Fix my OCD

### PR DESCRIPTION
**Pull request by TheSilentPro**

### CODE REVIEW

**Comment by untuned** [comment]
edit: nvm i read the commit wrong

**Comment by Telesphoreo** [comment]
this is not OCD this is a typo

**Comment by TheSilentPro** [comment]
> this is not OCD this is a typo

It's a joke.

**Comment by robingall2910** [comment]
> 
> 
> > this is not OCD this is a typo
> 
> It's a joke.

with bad taste

**Comment by script-head** [comment]
it triggers my ocd

**Pull request merged**
