### PR TITLE
shove that shit back in

### PR DESCRIPTION
**Pull request by ajaxvp**

### CODE REVIEW

**Comment by ajaxvp** [comment]
DO NOT MERGE YET; I HAVE A FEW MORE CHECKS TO GO THROUGH

**Comment by lemonsked** [comment]
What is the point of this

**Comment by ncurran02** [comment]
Removing aero

**Comment by robingall2910** [comment]
well it got rejected by the lead dev SO

**Comment by ncurran02** [comment]
Oof

**Pull request closed without merging**
