### PR TITLE
Remove Paper Check - Closes #166

### LINKED ISSUE #166: remove paper check fix
title, refer to pr #165 & #163, not really needed despite we have paper, a modified version at https://github.com/TFPatches/Paper 

a patch can be made to remove the check

### PR DESCRIPTION
**Pull request by ncurran02**
I’m a genius.

### CODE REVIEW

**Review by lemonsked — COMMENTED** [review]
can we just patch paper and remove the warning thanks

**Comment by ajaxvp** [comment]
dont fuck up this time

**Comment by ajaxvp** [comment]
i definitely didnt touch this pr

**Comment by ncurran02** [comment]
> can we just patch paper and remove the warning thanks

The thing is, paper patched these so it wouldn’t work. Only servers running Bukkit or Spigot can use them.

**Comment by lemonsked** [comment]
yeah we’re using a custom version of paper so we can patch it to remove the patch that makes it not work

**Comment by robingall2910** [comment]
there's a file conflict, can't push bc i was thinking about it

**Comment by ncurran02** [comment]
Can't fix it anyway. The repository this was on got deleted.

**Pull request closed without merging**
