### PR TITLE
/cookie returns

### PR DESCRIPTION
**Pull request by ajaxvp**
Highly suggested on the forums.

https://totalfreedom.boards.net/thread/60226/re-add-cookie

### CODE REVIEW

**Comment by script-head** [comment]
added yup

**Comment by JeromSar** [comment]
Was this merged without review? The code doesn't seem to work. @ZeroEpoch1969 ?

**Comment by lemonsked** [comment]
Fixed in https://github.com/TFPatches/TotalFreedomMod/commit/6e7297e48f684c156a5138ee50b5c89d9795d21d?

**Comment by JeromSar** [comment]
I see

**Pull request merged**
